server:
  contextPath:
  port: 9877

### SSL setting
#server.ssl.key-store=classpath:rmqcngkeystore.jks
#server.ssl.key-store-password=rocketmq
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=rmqcngkey

rocketmq:
  config:
    #if this value is empty,use env value rocketmq.config.namesrvAddr  NAMESRV_ADDR | now, you can set it in ops page.default localhost:9876
    namesrvAddr: 127.0.0.1:9876
    #if you use rocketmq version < 3.5.8, rocketmq.config.isVIPChannel should be false.default true
    isVIPChannel:
    #rocketmq-console's data path:dashboard/monitor
    dataPath: /tmp/rocketmq-console/data
    #set it false if you don't want use dashboard.default true
    enableDashBoardCollect: true
    #set the message track trace topic if you don't want use the default one
    msgTrackTopicName:
    ticketKey: ticket
    #Must create userInfo file: ${rocketmq.config.dataPath}/users.properties if the login is required
    loginRequired: true

#spring.application.index=true
spring:
  application:
    name: @project.name@
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  config: classpath:logback.xml
